### ISSUE TITLE
hi~bro

### ISSUE THREAD

**Issue by mjlin1334** [RealSkyr0/ReInject-V4#1]
can you authorize me to use ReInject-V4?

**Comment by RealSkyr0** [comment]
Sure, click on HWID on the bottom left of the injector and paste your code here.

**Comment by mjlin1334** [comment]
S-1-5-21-2758405532-2508831758-1416018421-500
Thank you bro!

**Comment by RealSkyr0** [comment]
You've been verified. Enjoy!
